server:
  port: 8083

spring:
  application:
    name: medical-record-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000