server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
        - id: medical-record-service
          uri: lb://medical-record-service
          predicates:
            - Path=/api/records/**